//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_properties
    {
        public int id { get; set; }
        public string product_group_code { get; set; }
        public string property_code { get; set; }
        public string property { get; set; }
        public string property_type { get; set; }
    }
}
